### ISSUE TITLE
Home y ¿Quienes somos?

### ISSUE THREAD

**Issue by harepper** [lopezoliveraeddy/portal-a11ylab#1]
Logo y HTML del Home y Quines somos de la página de Nancy, porfavor organiza los archvos en el host y a partir de aquí subo los archivos individalmente con la ruta en donde van en los comentarios, gracias ChHangoleon

![logo1-default](https://user-images.githubusercontent.com/11412894/29202825-520b4272-7e31-11e7-853d-7ec5a3388df5.png)

[WWW.zip](https://github.com/lopezoliveraeddy/portal-a11ylab/files/1217039/WWW.zip)

**Comment by lopezoliveraeddy** [comment]
Listo ya está el código versionado e incluye los estilos y funcionalidades para accesibilidad
